# Site settings
title: J. Blagg - CS Portfolio - SNHU
email: jeffrey.blagg@snhu.edu
description: >-
  SNHU CS 499 - Computer Science Capstone ePortfolio
domain: jab-snhu.github.io
baseurl: ""
url: "https://jab-snhu.github.io"

# Build settings
theme: minima
plugins:
  - jekyll-feed

# Navigation links in header
header_pages:
  - code-review.markdown
  - software-design.markdown
  - algorithms.markdown
  - databases.markdown
